apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: tailspinspacegame26984.azurecr.io/web
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          ports:
          - containerPort: 8080
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: leaderboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: tailspinspacegame26984.azurecr.io/leaderboard
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          ports:
          - containerPort: 8080
